const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const EDIT_TASK_TEXT = "EDIT_TASK_TEXT";
const CLEAR_TASKS = "CLEAR_TASKS";
const CHANGE_TASK_CHECKED = "CHANGE_TASK_CHECKED";
const REMOVE_CHECKED = "REMOVE_CHECKED";
const CHANGE_SEARCH_VAL = "CHANGE_SEARCH_VAL";
const CHANGE_FILTER_VAL = "CHANGE_FILTER_VAL";
const EDIT_TASK = "EDIT_TASK";
const CHANGE_SORT_BY_ALP_VAL = "CHANGE_SORT_BY_ALP_VAL";
const SET_TASKS = "SET_TASKS";

const ACTION_TYPES = {
    ADD_TASK,
    DELETE_TASK,
    EDIT_TASK_TEXT,
    CLEAR_TASKS,
    CHANGE_TASK_CHECKED,
    REMOVE_CHECKED,
    CHANGE_SEARCH_VAL,
    CHANGE_FILTER_VAL,
    CHANGE_SORT_BY_ALP_VAL,
    EDIT_TASK,
    SET_TASKS,
}

export default ACTION_TYPES;